server: 
  port: 9004
spring: 
  application:  
    name: feng-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.40.131:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
