server: 
  port: 9004
spring: 
  application:  
    name: feng-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.53.66.20:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: 333555
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 106.53.66.20
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
