server:
  port: 9010
spring:
  application:
    name: feng-friend
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.53.66.20:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: 333555

  jpa:
    database: mysql
    show-sql: true
jwt:
  config:
    key: feng
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true

