server:
  port: 9001
spring:
  application:
    name: feng-base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.40.131:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true